"""Build a library of barred patterns that are known to fill.

Barred patterns are cheap to generate and mostly cannot be filled, which is
the same situation the American style was in.  There the answer was to use
published grids; here there is only one published grid, so the pattern has to
be earned instead: generate, check it against the rules, and then *try to fill
it*.  A pattern only enters the library if a real fill came out.

That is not a heuristic standing in for the real test -- it is the real test,
paid once here so that no user pays it again.  It also costs what it costs: a
pattern that fills does so in a second or two, and one that does not burns the
whole node budget first, so most of the running time is spent on rejects.

    python3 build_barred_library.py --want 60
"""

import argparse
import random
import time

from crossword.barred import pattern
from crossword.fill import Filler
from crossword.index import Index
from crossword.library import BARRED_PATH, Pattern, rules_for, save
from crossword.rules import validate
from crossword.words import load

BANNER = (
    "# Barred patterns, 12x12, generated rather than extracted.\n"
    "# Every one is symmetric, legal, and has been filled at least once.\n"
    "# Generated by build_barred_library.py.\n"
)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--want", type=int, default=60)
    parser.add_argument("--size", type=int, default=12)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--node-budget", type=int, default=20000)
    # Loosely-checked patterns both fill more often and fail faster, so this
    # is where the fill attempts are worth spending.  A published Mephisto
    # leaves 48 of its 144 cells uncrossed.
    parser.add_argument("--min-unchecked", type=int, default=34)
    # Generation is free next to a fill attempt, so this is tuned for how many
    # usable patterns come out rather than for how few draws are wasted.  With
    # columns drawn uniformly the default already reaches the shape of a real
    # grid -- 226 patterns per 3,000 draws leave at least 34 cells unchecked,
    # and the loosest reach 56 -- so there is nothing to correct for here.
    parser.add_argument("--openness", type=float, default=1.0)
    parser.add_argument("--words", default="crossword/UKACD.txt")
    parser.add_argument("--out", default=BARRED_PATH)
    args = parser.parse_args()

    rules = rules_for("barred")
    index = Index(load(args.words))
    rng = random.Random(args.seed)

    kept, drawn, tested = [], 0, 0
    started = time.time()
    while len(kept) < args.want:
        drawn += 1
        grid = pattern(args.size, openness=args.openness, rng=rng)
        if grid is None or validate(grid, rules):
            continue
        unchecked = args.size ** 2 - len(grid.checked_cells(rules.min_entry_length))
        if unchecked < args.min_unchecked:
            continue
        tested += 1
        filler = Filler(grid, index, rules=rules, seed=rng.randrange(1 << 30),
                        node_budget=args.node_budget, commonness=0.0)
        if not filler.fill(restarts=2):
            continue
        # The letters were only ever proof; the library stores geometry.
        kept.append(
            Pattern(
                size=args.size,
                blocks=frozenset(),
                right_bars=frozenset(grid.right_bars),
                bottom_bars=frozenset(grid.bottom_bars),
                uses=0,
                source=f"generated-{len(kept)}",
                valid=True,
            )
        )
        print(f"  {len(kept):3d}/{args.want}  after {tested} fill attempts, "
              f"{time.time() - started:.0f}s", flush=True)

    save(kept, args.out, banner=BANNER)
    print(f"\n{len(kept)} patterns from {drawn} draws and {tested} fill attempts "
          f"in {time.time() - started:.0f}s -> {args.out}")


if __name__ == "__main__":
    main()
