"""Extract an American grid library from a corpus of .xd puzzles.

    python3 build_us_library.py xd-puzzles.zip

Only geometry is read: which squares are blocked. No clue, answer or title is
taken from any puzzle. A block pattern is a functional layout rather than
expressive content, which is the same basis on which the British library holds
Guardian patterns.

American grids, unlike British ones, are barely reused -- and the more of the
corpus is read the clearer that becomes -- so there is no usage count worth
recording and the library is a sample rather than a census. Patterns are
spread evenly across block counts, since taking the first N would draw them
all from one publication and one era.
"""

import collections
import random
import re
import sys
import zipfile

from crossword import library
from crossword.grid import Grid
from crossword.rules import RuleSet, validate

US = RuleSet(max_consecutive_unchecked=0, min_checked_fraction=1.0)
OUT = "crossword/grids-us.txt"
LIMIT = 2500


def grid_of(text):
    """The block pattern of an .xd puzzle: '#' is a block, anything else white."""
    rows, started = [], False
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            if started:
                break
            continue
        if re.fullmatch(r"[A-Z#_.]+", stripped):
            started = True
            rows.append(stripped.replace("_", "#").replace(".", "#"))
        elif started:
            break
    if len(rows) < 5 or len({len(r) for r in rows}) != 1:
        return None
    if len(rows) != len(rows[0]):
        return None
    return Grid.parse("\n".join(rows).lower())


def main(archive):
    with zipfile.ZipFile(archive) as bundle:
        wanted = [name for name in bundle.namelist() if name.endswith(".xd")]
        pubs = collections.Counter(
            name.split("/")[1] for name in wanted if name.startswith("gxd/"))
        print(f"{len(wanted)} puzzles across {len(pubs)} publications")

        seen, rejected, read = {}, collections.Counter(), 0
        for name in sorted(wanted):
            try:
                grid = grid_of(bundle.read(name).decode("utf-8", "replace"))
            except (KeyError, ValueError, OSError):
                continue
            if grid is None or grid.size != 15:
                continue
            read += 1
            problems = {v.rule for v in validate(grid, US)}
            if problems:
                rejected.update(problems)
                continue
            seen.setdefault(frozenset(grid.blocks), (grid, name))
        print(f"  ...{len(seen)} distinct patterns so far", end="\r", flush=True)

    print(f"{read} were 15x15; {len(seen)} distinct patterns pass the rule set")
    print(f"rejected: {dict(rejected.most_common(5))}")

    # A random sample, which is proportional to the real distribution by
    # construction.  Spreading evenly across block counts instead was wrong:
    # it over-represented the extremes, and a 16-block grid is not something
    # anyone publishes.  Real ones cluster hard -- 36 and 38 blocks are 20%
    # and 22% of the corpus, and 30 to 44 covers 93% -- so a random draw looks
    # like American crosswords and an even one does not.  Sampling patterns
    # rather than puzzles spreads publication and era for free.
    pool = [(blocks, grid, name) for blocks, (grid, name) in seen.items()]
    pool.sort(key=lambda item: item[2])          # deterministic before sampling
    chosen = random.Random(20260905).sample(pool, min(LIMIT, len(pool)))

    patterns = [
        library.Pattern(size=15, blocks=blocks, uses=0,
                        source=name.rsplit("/", 1)[-1][:-3], valid=True)
        for blocks, _grid, name in chosen
    ]
    library.save(patterns, OUT, banner=(
        "# Block patterns of published pre-1965 New York Times crosswords.\n"
        "# Geometry only: no clue, solution or title is reproduced here.\n"
        "# Generated by build_us_library.py.\n"
    ))
    counts = sorted(len(p.blocks) for p in patterns)
    print(f"\nwrote {len(patterns)} patterns to {OUT}")
    print(f"blocks {counts[0]}-{counts[-1]}, median {counts[len(counts)//2]}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "xd-puzzles.zip")
