"""How often each word has actually been used as a crossword answer.

The fill was drawn uniformly from all 221,835 UKACD entries, which is why
grids came out holding `librairie`, `goldless`, `ramuli` and `yeps`.  UKACD is
a word list, not a judgement about which words a solver should be expected to
know.

The judgement is in the corpus.  8,386 published Guardian puzzles contain
236,698 answers, and a word that appeared among them is one a professional
setter thought fair to ask for.  Only 25% of UKACD has ever appeared; the
other 75% is where all four of those offenders live.

This is a domain frequency, not a general English one, and the difference
matters in both directions.  It rewards crossword-friendly words -- vowel-rich,
awkward-letter-free -- somewhat beyond their ordinary currency, and `isle`,
`stye` and `stud` rank absurdly high by any other measure.  It also gives a
count of zero to perfectly ordinary words that simply have not come up.  So it
is a preference to be weighed, not a truth: `min_uses=1` is a reasonable floor
rather than a principled one, and the soft weighting matters more than the cut.

Built from the corpus by build_frequency.py; the result is committed, so using
it needs no corpus.
"""

from __future__ import annotations

import glob
import json
import math
import os
from collections import Counter

from .words import _fold

DEFAULT_PATH = os.path.join(os.path.dirname(__file__), "frequency.txt")
SCORES_PATH = os.path.join(os.path.dirname(__file__), "scores.txt")

# Zipf is log10(occurrences per billion words), so it is already a log scale;
# this only rescales it to reach about the same maximum as log1p(uses) does on
# the Guardian counts, which top out at 78 for "isle" -> 4.37.  Without it one
# source would silently outrank the other everywhere.
ZIPF_SCALE = 0.75


def load(path: str = DEFAULT_PATH) -> dict:
    """Read the table: word -> times used as a published answer."""
    counts = {}
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("#") or not line.strip():
                continue
            word, _, number = line.partition(" ")
            counts[word] = int(number)
    return counts


def save(counts: dict, path: str = DEFAULT_PATH) -> None:
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(
            "# Times each word has appeared as an answer in the Guardian\n"
            "# cryptic corpus.  Words absent from this file were never used.\n"
            "# Generated by build_frequency.py.  Geometry and counts only:\n"
            "# no clue or puzzle is reproduced.\n"
        )
        for word in sorted(counts, key=lambda w: (-counts[w], w)):
            handle.write(f"{word} {counts[word]}\n")


def extract(corpus: str, vocabulary=None) -> dict:
    """Count answers across a corpus of Guardian JSON.

    `vocabulary` restricts the result to words we can actually use as fill.
    Answers outside it are overwhelmingly proper nouns and phrases, which the
    loader excludes anyway.
    """
    counts: Counter = Counter()
    for path in sorted(glob.glob(os.path.join(corpus, "**", "*.JSON"), recursive=True)):
        try:
            with open(path, encoding="utf-8") as handle:
                data = json.load(handle)
        except (ValueError, OSError):
            continue
        for entry in data.get("entries", []):
            word = _fold(entry.get("solution") or "")
            if 3 <= len(word) <= 15:
                counts[word] += 1
    if vocabulary is not None:
        counts = Counter({w: n for w, n in counts.items() if w in vocabulary})
    return dict(counts)


# -- using it --------------------------------------------------------------


def filter_entries(entries, counts: dict, min_uses: int = 0):
    """Drop entries used fewer than `min_uses` times.  Superseded by `select`.

    Kept because it names the Guardian count directly, which `select`'s floor
    deliberately does not.
    """
    if min_uses <= 0:
        return list(entries)
    return [entry for entry in entries if counts.get(entry.text, 0) >= min_uses]


def select(entries, scores: dict, counts: dict, *,
           min_score: float = 0.0, max_uses: int = None):
    """The fill vocabulary for one puzzle: a floor, a ceiling, or both.

    The two bounds read different signals, and that is the point.

    The **floor** asks "will a solver know this word", so it reads the
    combined score, where a word is rescued by either source.  Reading the
    Guardian count instead would throw away `windscreen` and `pavement` for
    never having come up.

    The **ceiling** asks "is this word tired", which is a question only the
    Guardian count can answer.  General frequency says `isle` and `hesitate`
    are equally ordinary; the corpus says one has been an answer 78 times and
    the other 3.  Above about 20 uses the list is pure crosswordese -- isle,
    extra, star, blue, bridge, echo, stud, oleo -- and a setter may reasonably
    want none of it, which no general corpus could tell them.

    Both are hard cuts, so both cost coverage.  Sizes at each floor, for
    judging how far is too far:

        min_score   words    15-letter words
            0.0    221,835         4,426
            1.0     84,268           895
            2.0     33,687           125     <- too thin to fill with
    """
    kept = []
    for entry in entries:
        if scores.get(entry.text, 0.0) < min_score:
            continue
        if max_uses is not None and counts.get(entry.text, 0) > max_uses:
            continue
        kept.append(entry)
    return kept


def describe(entries, counts: dict) -> str:
    """A one-line summary of how common a set of entries is."""
    if not entries:
        return "no entries"
    used = [counts.get(entry.text, 0) for entry in entries]
    seen = sum(1 for n in used if n)
    return (
        f"{len(entries)} entries, {seen} ({100 * seen // len(entries)}%) "
        f"published at least once"
    )


# -- the combined score ----------------------------------------------------
#
# Guardian counts alone are a domain frequency: they rank `isle`, `stye` and
# `stud` absurdly high and give zero to ordinary words that simply have not
# come up.  A general corpus alone has the opposite failure -- it has never
# heard of a phrase, and 42,125 of UKACD's entries are phrases.
#
# So take the better of the two.  Neither source can condemn a word on its
# own, and the phrase routing falls out for free: a general corpus scores a
# concatenated phrase at zero, so `max` leaves the Guardian count in charge
# of exactly the entries we wanted it to own.


def guardian_scores(counts: dict) -> dict:
    """The Guardian counts alone, in log units."""
    return {word: math.log1p(n) for word, n in counts.items()}


def build_scores(vocabulary, counts: dict) -> dict:
    """Combine Guardian usage with general English frequency.

    Needs `wordfreq`, which is a build-time dependency only: the result is
    written to scores.txt and committed, so nothing at run time imports it.
    """
    from wordfreq import zipf_frequency

    scores = {}
    for word in vocabulary:
        guardian = math.log1p(counts.get(word, 0))
        general = ZIPF_SCALE * zipf_frequency(word, "en")
        best = max(guardian, general)
        if best > 0:
            scores[word] = round(best, 3)
    return scores


def load_scores(path: str = SCORES_PATH) -> dict:
    """Read the combined table: word -> familiarity, in log units."""
    scores = {}
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("#") or not line.strip():
                continue
            word, _, number = line.partition(" ")
            scores[word] = float(number)
    return scores


def save_scores(scores: dict, path: str = SCORES_PATH) -> None:
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(
            "# Combined familiarity score per word, in log units:\n"
            "#   max(log1p(Guardian answer uses), 0.75 * wordfreq Zipf)\n"
            "# Higher is more ordinary.  Absent words score 0.\n"
            "# Generated by build_frequency.py; needs wordfreq, which run\n"
            "# time does not.\n"
        )
        for word in sorted(scores, key=lambda w: (-scores[w], w)):
            handle.write(f"{word} {scores[word]}\n")
