"""How often each word has actually been used as a crossword answer.

The fill was drawn uniformly from all 221,835 UKACD entries, which is why
grids came out holding `librairie`, `goldless`, `ramuli` and `yeps`.  UKACD is
a word list, not a judgement about which words a solver should be expected to
know.

The judgement is in the corpus.  8,386 published Guardian puzzles contain
236,698 answers, and a word that appeared among them is one a professional
setter thought fair to ask for.  Only 25% of UKACD has ever appeared; the
other 75% is where all four of those offenders live.

This is a domain frequency, not a general English one, and the difference
matters in both directions.  It rewards crossword-friendly words -- vowel-rich,
awkward-letter-free -- somewhat beyond their ordinary currency, and `isle`,
`stye` and `stud` rank absurdly high by any other measure.  It also gives a
count of zero to perfectly ordinary words that simply have not come up.  So it
is a preference to be weighed, not a truth: `min_uses=1` is a reasonable floor
rather than a principled one, and the soft weighting matters more than the cut.

Built from the corpus by build_frequency.py; the result is committed, so using
it needs no corpus.
"""

from __future__ import annotations

import glob
import json
import os
from collections import Counter

from .words import _fold

DEFAULT_PATH = os.path.join(os.path.dirname(__file__), "frequency.txt")


def load(path: str = DEFAULT_PATH) -> dict:
    """Read the table: word -> times used as a published answer."""
    counts = {}
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            if line.startswith("#") or not line.strip():
                continue
            word, _, number = line.partition(" ")
            counts[word] = int(number)
    return counts


def save(counts: dict, path: str = DEFAULT_PATH) -> None:
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(
            "# Times each word has appeared as an answer in the Guardian\n"
            "# cryptic corpus.  Words absent from this file were never used.\n"
            "# Generated by build_frequency.py.  Geometry and counts only:\n"
            "# no clue or puzzle is reproduced.\n"
        )
        for word in sorted(counts, key=lambda w: (-counts[w], w)):
            handle.write(f"{word} {counts[word]}\n")


def extract(corpus: str, vocabulary=None) -> dict:
    """Count answers across a corpus of Guardian JSON.

    `vocabulary` restricts the result to words we can actually use as fill.
    Answers outside it are overwhelmingly proper nouns and phrases, which the
    loader excludes anyway.
    """
    counts: Counter = Counter()
    for path in sorted(glob.glob(os.path.join(corpus, "**", "*.JSON"), recursive=True)):
        try:
            with open(path, encoding="utf-8") as handle:
                data = json.load(handle)
        except (ValueError, OSError):
            continue
        for entry in data.get("entries", []):
            word = _fold(entry.get("solution") or "")
            if 3 <= len(word) <= 15:
                counts[word] += 1
    if vocabulary is not None:
        counts = Counter({w: n for w, n in counts.items() if w in vocabulary})
    return dict(counts)


# -- using it --------------------------------------------------------------


def filter_entries(entries, counts: dict, min_uses: int = 0):
    """Drop entries used fewer than `min_uses` times.

    A hard floor, and blunt: it removes words the search can then never
    reach.  Set it low.  At `min_uses=3` there are 131 eleven-letter words
    left and at 5 there are 8 of length fourteen, which is not a dictionary
    any more.
    """
    if min_uses <= 0:
        return list(entries)
    return [entry for entry in entries if counts.get(entry.text, 0) >= min_uses]


def describe(entries, counts: dict) -> str:
    """A one-line summary of how common a set of entries is."""
    if not entries:
        return "no entries"
    used = [counts.get(entry.text, 0) for entry in entries]
    seen = sum(1 for n in used if n)
    return (
        f"{len(entries)} entries, {seen} ({100 * seen // len(entries)}%) "
        f"published at least once"
    )
