"""SATOR squares: word squares that read the same in all four directions.

    S A T O R
    A R E P O
    T E N E T
    O P E R A
    R O T A S

Two symmetries at once. It is a symmetric word square, grid[r][c] ==
grid[c][r], so the columns are the rows; and it is unchanged by a 180-degree
turn, grid[r][c] == grid[n-1-r][n-1-c]. Together those force row n-1-r to be
the reverse of row r, which collapses the problem: the square is fixed by its
top half, every row of which must be a word whose reverse is also a word, and
for odd n the middle row must additionally be a palindrome.

That is why this is fast where a plain word square is not. An ordinary 5x5
searches for five words; this searches for two, and reads the rest off. The
binding resource is not the dictionary's size but how many *reversible* words
it holds -- 821 five-letter ones in Wiktionary against 288 in UKACD, and only
309 six-letter ones, which is what puts 6x6 out of reach in ordinary words.

Squares are reported best-first by familiarity, on the weakest word rather
than the average: a square is only as recognisable as its most obscure entry,
and averaging lets four ordinary words hide a fifth nobody has met.

    python3 sator.py 5
    python3 sator.py 6 --proper --top 20
"""

from .canonical import deduplicate           # noqa: F401  (re-exported)


def solve(words, n, limit=None):
    """Every SATOR square of order n over `words`. Exhaustive unless limited."""
    reversible = [w for w in words if w[::-1] in words]
    half = (n + 1) // 2
    by_prefix = {}
    for word in reversible:
        for cut in range(len(word) + 1):
            by_prefix.setdefault(word[:cut], []).append(word)

    grid = [[None] * n for _ in range(n)]
    found = []

    def place(row, word):
        written = []
        for column, letter in enumerate(word):
            # One letter lands in up to four cells: the symmetry group is
            # generated by the transpose and the half-turn.
            for cell in ((row, column), (column, row),
                         (n - 1 - row, n - 1 - column),
                         (n - 1 - column, n - 1 - row)):
                i, j = cell
                if grid[i][j] is None:
                    grid[i][j] = letter
                    written.append(cell)
                elif grid[i][j] != letter:
                    for x, y in written:
                        grid[x][y] = None
                    return None
        return written

    def recurse(row):
        if row == half:
            rows = ["".join(grid[i]) for i in range(n)]
            if all(word in words for word in rows):
                found.append(rows)
            return limit is not None and len(found) >= limit
        prefix = ""
        for column in range(n):
            if grid[row][column] is None:
                break
            prefix += grid[row][column]
        for word in by_prefix.get(prefix, ()):
            if n % 2 and row == half - 1 and word != word[::-1]:
                continue
            written = place(row, word)
            if written is None:
                continue
            stop = recurse(row + 1)
            for x, y in written:
                grid[x][y] = None
            if stop:
                return True
        return False

    recurse(0)
    return found
