"""Build a library of barred patterns that are known to fill.

Barred patterns are cheap to generate and mostly cannot be filled, which is
the same situation the American style was in.  There the answer was to use
published grids; here there is only one published grid, so the pattern has to
be earned instead: generate, check it against the rules, and then *try to fill
it*.  A pattern only enters the library if a real fill came out.

That is not a heuristic standing in for the real test -- it is the real test,
paid once here so that no user pays it again.  It also costs what it costs: a
pattern that fills does so in a second or two, and one that does not burns the
whole node budget first, so most of the running time is spent on rejects.

    python3 build_barred_library.py --want 60
"""

import argparse
import random
import time

# Run as `python3 tools/build_barred_library.py` from the repository root: Python puts this
# directory on sys.path, not its parent, so the root goes on explicitly.
import os as _os
import sys as _sys

_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))


from crossword.barred import pattern
from crossword.fill import Filler
from crossword.index import Index
from crossword.library import BARRED_PATH, Pattern, rules_for, save
from crossword.rules import validate
from crossword.words import load

BANNER = (
    "# Barred patterns, 12x12, generated rather than extracted.\n"
    "# Every one is symmetric, legal, and has been filled at least once.\n"
    "# Generated by build_barred_library.py.\n"
)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--want", type=int, default=60)
    parser.add_argument("--size", type=int, default=12)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--node-budget", type=int, default=20000)
    # Where the published grids are: a Mephisto leaves 48 of its 144 cells
    # uncrossed and an Azed 54.  This was 34 while the shape was being guessed
    # at, and patterns that tight fill about half the time; at the real shape
    # they fill essentially always, so the floor is worth far more than any
    # amount of patience below it.
    parser.add_argument("--min-unchecked", type=int, default=None,
                        metavar="N",
                        help="floor on uncrossed cells (default: 30%% of the "
                             "grid, which is where the published 12x12s sit -- "
                             "a Mephisto leaves 48 of 144 and an Azed 54)")
    # Generation is free next to a fill attempt -- 15,000 draws take six
    # seconds -- so this is tuned for how many patterns come out at the floor
    # above, not for how few draws are wasted.  Once every entry has to stay
    # within a third unchecked, that yield is about 24 per 15,000, and pushing
    # openness higher only makes it rarer without making the grids denser.
    parser.add_argument("--openness", type=float, default=1.3)
    # Four-letter entries are legal -- an Azed has six -- but they are a
    # garnish, not the fabric: 8% of published entries against 36% of what an
    # unweighted sampler produces.  Penalising them is what brings the entry
    # count, the mean length and the share of short entries onto the published
    # figures together, rather than one at a time.
    parser.add_argument("--short-bias", type=float, default=0.15)
    parser.add_argument("--words", default="crossword/UKACD.txt")
    parser.add_argument("--out", default=BARRED_PATH)
    args = parser.parse_args()

    if args.min_unchecked is None:
        # Where the published grids are, as a proportion rather than a count,
        # so it means the same thing at any size.
        args.min_unchecked = round(0.30 * args.size ** 2)
    rules = rules_for("barred")
    index = Index(load(args.words))
    rng = random.Random(args.seed)

    kept, drawn, tested = [], 0, 0
    started = time.time()
    while len(kept) < args.want:
        drawn += 1
        grid = pattern(args.size, openness=args.openness,
                       short_bias=args.short_bias, rng=rng)
        if grid is None or validate(grid, rules):
            continue
        unchecked = args.size ** 2 - len(grid.checked_cells(rules.min_entry_length))
        if unchecked < args.min_unchecked:
            continue
        tested += 1
        filler = Filler(grid, index, rules=rules, seed=rng.randrange(1 << 30),
                        node_budget=args.node_budget, commonness=0.0)
        if not filler.fill(restarts=2):
            continue
        # The letters were only ever proof; the library stores geometry.
        kept.append(
            Pattern(
                size=args.size,
                blocks=frozenset(),
                right_bars=frozenset(grid.right_bars),
                bottom_bars=frozenset(grid.bottom_bars),
                uses=0,
                source=f"generated-{len(kept)}",
                valid=True,
            )
        )
        print(f"  {len(kept):3d}/{args.want}  after {tested} fill attempts, "
              f"{time.time() - started:.0f}s", flush=True)

    save(kept, args.out, banner=BANNER)
    print(f"\n{len(kept)} patterns from {drawn} draws and {tested} fill attempts "
          f"in {time.time() - started:.0f}s -> {args.out}")


if __name__ == "__main__":
    main()
